[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"

[tool.black]
exclude = '''
/\.github/
/\.travis/
/audio_cache/
/bin/
/config/
/data/
/logs/
\.gitignore
\.travis.yml
/musicbot/__pycache__/
'''
